### ISSUE TITLE
Homeassistant raspberry

### ISSUE THREAD

**Issue by madspeed** [jstebbins/hassio-vantage2mqtt#1]
Hi!
Is there any chance to install your addon on raspberry Pi homeassitant?

I have problems with command "scp -r Dockerfile config.json requirements.txt src/ root@homeassistant:addons/vantage2mqtt/"

**Comment by jstebbins** [comment]
I use it on RPi 4 with the 32bit homeassistant OS release.
https://www.home-assistant.io/hassio/installation/

It's been a while since I've rebuilt vantage2mqtt addon, and homeassistant does make breaking changes occasionally.  But scp should still work.  I assume you verified that ssh to HA works and you created the necessary addons/vantage2mqtt directory?

Also, a heads up.  I've got some changes planned in the not too distant future.  I would like to expose vantage tasks as mqtt switches.  After using the system for a while, I've determined that it would be better for my usage to directly control vantage tasks instead of controlling through wall switch buttons that are tied to tasks.  It's more flexible.  

I was originally planning to change the naming convention for mqtt entities so that I could distinguish vantage buttons, relays, tasks, etc by looking at the entity name (these are all switches as far as HA mqtt is concerned).  But that would break any existing installation because the existing entity names would change.  I figured I was probably the only person using this addon, and could fix things up as I did the switch to using tasks.  But it appears there is actually at least one other person interested :grinning: So I'll only be modifying the naming for tasks and leave the rest alone.  Not ideal, but I would hate to break someone else's installation.

**Comment by madspeed** [comment]
I have managed to install the addon, but get an error, do you have any ideas what that means?
[

> s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> DEBUG:main:Skipping device cache
> DEBUG:InFusionConfig:InFusionConfig init
> DEBUG:InFusionConfig:Reading devices configuration...
> DEBUG:InFusionConfig:Try Design Center configuration SiteName.dc
> WARNING:InFusionConfig:Could not read SiteName.dc, [Errno 2] No such file or directory: 'SiteName.dc'
> DEBUG:InFusionConfig:Lookup _aci service via zeroconf
> WARNING:zeroconf:packets() made no progress adding records; returning
> WARNING:zeroconf:packets() made no progress adding records; returning
> WARNING:zeroconf:packets() made no progress adding records; returning
> WARNING:zeroconf:packets() made no progress adding records; returning
> CRITICAL:main:Error: Failed to read inFusion memory
> [cmd] /vantage2mqtt.py exited 1
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.

**Comment by jstebbins** [comment]
The critical error is this one:

> CRITICAL:main:Error: Failed to read inFusion memory


By default, the addon tries to locate your Vantage Infusion via zero
conf.  It appears it was not able to find it (timed out while
searching).  

You can also configure it's IP address of the Infusion in the
configuration options for the addon. But if it could not be found via
zeroconf, I'm wondering if you have one of the more recent Infusions
that is network connected or an older one that can only be controlled
via RS232 port.  This addon requires a recent Infusion with network
capability and that it be plugged in to your network.

Re-reading my README file, I see I completely neglected to mention any
information about the required Vantage Infusion model and Vantage
system setup.  I'll update that to make this more clear.

**Comment by madspeed** [comment]
Here is what the config looks like:

> vantage:
>   site-name: office
>   zeroconf: true
>   ip: 10.6.0.2
>   command_port: 3001
>   config_port: 2001
>   skip-device-cache: true
>   dcconfig: SiteName.dc
>   dccache: false
>   debug: true
>   short-names: false
>   buttons: true
>   lights: true
>   relays: true
>   motors: false
> mqtt:
>   ip: 10.17.0.225
>   port: 1883
>   username: mosquitto
>   password: mosquitto

And here is the vantage web interface, it is definately network connected:

![image](https://user-images.githubusercontent.com/61581394/107609232-635a2380-6c4f-11eb-8d84-d6eb3b7b6af7.png)

**Comment by jstebbins** [comment]
I currently have it coded to use either zeroconf or IP & port.  If zeroconf fails it does not fall back to using IP & port.  So try setting zeroconf to false in your config.  Also if you are familiar with telnet, you can test the command port with
> telnet 10.6.0.2 3001

Should connect to the infusion and once connected

> help

Should show a list of commands supported by the Infusion command interface

**Comment by madspeed** [comment]
This is what I get:
> help
>   BTN <button vid>
>   BTNPRESS <button vid>
>   BTNRELEASE <button vid>
>   LOAD <load vid> <level (0-100)>
>   RAMPLOAD <load vid> <level (0-100)> <seconds>
>   GETLOAD <load vid>
>   LED <button vid> <color1 (0-255)> <color2> <color3> <offcolor1> <offcolor2 (0-                                                                               255)> <offcolor3> <blinkrate (FAST/MEDIUM/SLOW/VERYSLOW/OFF)>
>   GETLED <button vid>
>   TASK <task vid> <eventType (PRESS/RELEASE/HOLD/TIMER/DATA/POSITION/INRANGE/OUT                                                                               OFRANGE/TEMPERATURE/DAYMODE/FANMODE/OPERATIONMODE/CONNECT/DISCONNECT/BOOT/LEARN/                                                                               CANCEL/NONE)>
>   GETTASK <task vid>
>   STATUS <type (LOAD/LED/BTN/TASK/TEMP/THERMFAN/THERMOP/THERMDAY/SLIDER/TEXT/VAR                                                                               IABLE/BLIND/PAGE/LEDSTATE/IMAGE/WIND/LIGHT/CURRENT/POWER/ALL/NONE)>
>   GETTEMP <temperature vid>
>   THERMTEMP <thermostat vid> <type (COOL/HEAT)> <temperature>
>   GETTHERMTEMP <thermostat vid> <type (INDOOR/OUTDOOR/COOL/HEAT)>
>   THERMFAN <thermostat vid> <fan (ON/AUTO)>
>   GETTHERMFAN <thermostat vid>
>   THERMOP <thermostat vid> <op mode (OFF/COOL/HEAT/AUTO)>
>   GETTHERMOP <thermostat vid>
>   THERMDAY <thermostat vid> <day mode (DAY/NIGHT)>
>   GETTHERMDAY <thermostat vid>
>   SLIDER <slider vid> <level (0-100)>
>   GETSLIDER <slider vid>
>   TEXT <text vid> <text>
>   GETTEXT <text vid>
>   VARIABLE <variable vid> <value "text"/number>
>   GETVARIABLE <variable vid>
>   GETFIELD <Obj vid> <field name>
>   GETSENSOR <Obj vid>
>   GETLIGHT <Obj vid>
>   GETWIND <Obj vid>
>   GETCURRENT <Obj vid>
>   GETPOWER <Obj vid>
>   BLIND <Obj vid> <control (OPEN/CLOSE/STOP/POS)> <position>
>   GETBLIND <Obj vid>
>   INVOKE <Obj vid> <interface.method> <parameter> ...
>   !LOAD <type (M/S)> <controller> <bus> <device> <load/count> <level (0-100)>
>   !RAMPLOAD <type (M/S)> <controller> <bus> <device> <load/count> <level (0-100)                                                                               > <seconds>
>   !GETLOAD <type (M/S)> <controller> <bus> <device> <load/count>
>   ADDSTATUS <vid> ...
>   DELSTATUS [<vid> ...]
>   LISTSTATUS
>   ECHO <text>
>   VERSION
>   GETCOUNT
>   DELIMITER <Hex Byte 1> [<Hex Byte 2>]
>   LOG  [<controller> ... ] [CONTROLLER] [TYPE] [TIME] [SOURCE] [FULL]   [DEBUG]                                                                                [DUMP] [INFO] [WARNING] [ERROR] [FATAL] [TASK] [DEVICE] [QUERY] [PROF]
>   DUMP <controller> [CONTROLLER] [TYPE] [TIME] [SOURCE] [FULL]   [DEBUG] [DUMP]                                                                                [INFO] [WARNING] [ERROR] [FATAL] [TASK] [DEVICE] [QUERY] [PROF]
>   ELSIZE [<controller>] <type (STATUS/STATUSEX/AUTOMATION/SYSTEM/EVENT/MODCOM/ST                                                                               ATCOM)> <size>
>   ELGETSIZE [<controller>] <type (STATUS/STATUSEX/AUTOMATION/SYSTEM/EVENT/MODCOM                                                                               /STATCOM)>
>   ELAGG [<controller>] <state (ON/OFF)>
>   ELENABLE [<controller>] <type (STATUS/STATUSEX/AUTOMATION/SYSTEM/EVENT/MODCOM/                                                                               STATCOM)> <state (ON/OFF)>
>   ELDUMP <type (STATUS/STATUSEX/AUTOMATION/SYSTEM/EVENT/MODCOM/STATCOM)> [PERCEN                                                                               T] [CONTROLLER] [TIME] [TYPE] [HEX] [FULL] [<filter>]
>   ELLOG <type (STATUS/STATUSEX/AUTOMATION/SYSTEM/EVENT/MODCOM/STATCOM)> [PERCENT                                                                               ] [CONTROLLER] [TIME] [TYPE] [HEX] [FULL] <state (ON/OFF) [<filter>]
>   LOGIN <user name> <password>

**Comment by madspeed** [comment]
Disabled zeroconf:

> > DEBUG:main:Skipping device cache
> DEBUG:InFusionConfig:InFusionConfig init
> DEBUG:InFusionConfig:Reading devices configuration...
> DEBUG:InFusionConfig:Try Design Center configuration SiteName.dc
> WARNING:InFusionConfig:Could not read SiteName.dc, [Errno 2] No such file or directory: 'SiteName.dc'
> DEBUG:InFusionConfig:Try inFusion Memory card ip 10.6.0.2:2001
> DEBUG:InFusionConfig:read size 93
> Traceback (most recent call last):
>   File "/vantage2mqtt.py", line 658, in <module>
>     main.run()
>   File "/vantage2mqtt.py", line 633, in run
>     vantage_cfg = self.read_vantage_config()
>   File "/vantage2mqtt.py", line 525, in read_vantage_config
>     return InFusionConfig(self.cfg["vantage"], xml_config_file=dc)
>   File "/infusion.py", line 165, in __init__
>     self.read_infusion_memory(ip, port)
>   File "/infusion.py", line 267, in read_infusion_memory
>     xml_root = ET.fromstring(self.xml_config)
>   File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
>     return parser.close()
> xml.etree.ElementTree.ParseError: no element found: line 1, column 0
> [cmd] /vantage2mqtt.py exited 1
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.

**Comment by jstebbins** [comment]
It seems your infusion isn't responding to zeroconf the same as mine and it isn't responding on port 2001 (where the config is retrieved from) the same way mine does.  

It is responding with some data on port 2001, but it's not config data.  Unfortunately, there isn't any debug logging of what it returned.  How are you with python?  It might help to see what is being returned.  In src/infusion.py around line 260 add a debug statement like this
```
            config = config.decode('ascii')
            self._log.debug("read %s", config)
            config = config[config.find('<?File Encode="Base64" /'):]
```
I expect the above will show some kind of error in the text returned from the infusion.

A couple possibilities occur to me.  One, maybe they changed the firmware at some point and our infusion's just don't work the same. Or the other, maybe whoever set up your infusion didn't save the config to the sdcard in the infusion.  Standard practice is to save the XML config file to the infusions sdcard using the Vantage Design Center software during system configuration.  This is what I attempt to read from the device.

Do you happen to have the Design Center software or a copy of the XML config file used to set up your system?

**Comment by 67pmartin** [comment]
Hi, 
Love your work, just what I was looking for. I have a Vantage system at home and was having problems integrating with other systems so I could do some cool automation. I had some initial problems however once I set zeroconfig to false things fire into life. New to HA too so does not help. I'll let you know how things progress, looks like everything from the vantage system is now visible in HA either as a device or an entity. My only question is what is zeroconfig?

**Comment by jstebbins** [comment]
Zeroconfig is also called multicast DNS, avahi, and rendezvous.  It's a way for devices to advertise services they provide on your network without needing a central server.

Funny thing, zeroconfig just quit working for me about a week ago.  I hadn't even upgraded the software on my HA instance, so must be a problem with my network equipment.  Haven't had time to try to run it down yet.

Another thing to keep in mind with Vantage, the latest software update locks down the unencrypted ports on the Infusion.  You can open them back up if you have the Design Center software. So if you have any work done on the system, check that the plugin is still working when they are done. I'm going to add the ability to connect through the encrypted ports eventually. Just need to find the time.
